Repository prog-g/dcc-report, pull requests merged in 2020-02, with the labels that each got.

#20 gh-pages にデプロイできるようにする
  package.json
  yarn.lock
Labels: enhancement, yarn upgrade

#12 グラフを書けるようにする
  src/App.tsx
  src/Graph.tsx
  src/Note.tsx
  src/Timeline.tsx
  src/declares.d.ts
  src/lib/canvas.ts
  src/lib/note.ts
Labels: enhancement

#24 Fix download function
  src/lib/util.ts
Labels: fix
