Repository prog-g/dcc-report, pull requests merged in 2020-07, with the labels that each got.

#49 Switching to babel
  babel.config.js
  package.json
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: refactor, yarn upgrade

#38 IDと氏名を記入する欄を作る
  src/App.tsx
  src/NameEntry.tsx
  src/style.css
Labels: enhancement

#53 Fix for lint
  README.md
  src/Graph.tsx
  src/NoteList.tsx
  src/lib/canvas.ts
  src/style.css
Labels: refactor
